
// Action types
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const INCREMENT_IF_ODD = 'INCREMENT_IF_ODD'

export const INCREMENT_ASYNC = 'INCREMENT_ASYNC'
export const CANCEL_INCREMENT_ASYNC = 'CANCEL_INCREMENT_ASYNC'

export const COUNTDOWN_TERMINATED = 'COUNTDOWN_TERMINATED'


export const QUERY_TBLIST = 'QUERY_TBLIST'
export const UPDATE_QUERYKEY_TBLIST = 'UPDATE_QUERYKEY_TBLIST'
export const QUERY_TBLIST_SUCCESS = 'QUERY_TBLIST_SUCCESS'
export const CREATE_TBLIST = 'CREATE_TBLIST'
export const CREATE_TBLIST_SUCCESS = 'CREATE_TBLIST_SUCCESS'
export const UPDATE_TBLIST = 'UPDATE_TBLIST'
export const UPDATE_TBLIST_SUCCESS = 'UPDATE_TBLIST_SUCCESS'
export const DELETE_TBLIST = 'DELETE_TBLIST'
export const DELETE_TBLIST_SUCCESS = 'DELETE_TBLIST_SUCCESS'

export const SHOW_TBLIST_LOADING = 'SHOW_TBLIST_LOADING'
export const SHOW_TBLIST_MODAL = 'SHOW_TBLIST_MODAL'
export const HIDE_TBLIST_MODAL = 'HIDE_TBLIST_MODAL'


export const QUERY_DATASRC = 'QUERY_DATASRC'
export const UPDATE_QUERYKEY_DATASRC = 'UPDATE_QUERYKEY_DATASRC'
export const QUERY_DATASRC_SUCCESS = 'QUERY_DATASRC_SUCCESS'
export const QUERY_DATASRC_FAILURE = 'QUERY_DATASRC_FAILURE'
export const CREATE_DATASRC = 'CREATE_DATASRC'
export const CREATE_DATASRC_SUCCESS = 'CREATE_DATASRC_SUCCESS'
export const CREATE_DATASRC_FAILURE = 'CREATE_DATASRC_FAILURE'

export const UPDATE_DATASRC = 'UPDATE_DATASRC'
export const UPDATE_DATASRC_SUCCESS = 'UPDATE_DATASRC_SUCCESS'
export const DELETE_DATASRC = 'DELETE_TBLIST'
export const DELETE_DATASRC_SUCCESS = 'DELETE_DATASRC_SUCCESS'
export const RESET_DATASRC = 'RESET_DATASRC'
export const RESET_DATASRC_MSG = 'RESET_DATASRC_MSG'

export const SHOW_DATASRC_LOADING = 'SHOW_DATASRC_LOADING'
export const SHOW_DATASRC_MODAL = 'SHOW_DATASRC_MODAL'
export const HIDE_DATASRC_MODAL = 'HIDE_DATASRC_MODAL'
export const SHOW_DATASRC_INDEX_MODAL = 'SHOW_DATASRC_INDEX_MODAL'
export const HIDE_DATASRC_INDEX_MODAL = 'HIDE_DATASRC_INDEX_MODAL'
